### ISSUE TITLE
zita-resampler includes host /usr/lib64 path (target-host contamination)

### ISSUE THREAD

**Issue by MaxPayne86** [schnitzeltony/meta-qt5-extra#41]
I'm using your recipe [here](https://github.com/MaxPayne86/meta-moddevices/blob/master/recipes-sw/zita-resampler/zita-resampler_1.6.0.bb) 

ERROR: zita-resampler-1.6.0-r0 do_package_qa: QA Issue: zita-resampler: The compile log indicates that host include and/or library paths were used.
         Please check the log '/home/softin/Work/RASP/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/zita-resampler/1.6.0-r0/temp/log.do_compile' for more information. [compile-host-path]
ERROR: zita-resampler-1.6.0-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: zita-resampler-1.6.0-r0 do_package_qa: Function failed: do_package_qa
ERROR: Logfile of failure stored in: /home/softin/Work/RASP/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/zita-resampler/1.6.0-r0/temp/log.do_package_qa.28778
ERROR: Task (/home/softin/Work/RASP/meta-moddevices/recipes-sw/zita-resampler/zita-resampler_1.6.0.bb:do_package_qa) failed with exit code '1'

The log.compile then reports

...
arm-poky-linux-gnueabi-g++  -march=armv7ve -marm -mfpu=neon-vfpv4  -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/home/softin/Work/RASP/build/tmp/sysroots/raspberrypi2 -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed  -L/home/softin/Work/RASP/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/zita-resampler/1.6.0-r0/zita-resampler-1.6.0/libs -L/usr/local/lib64 -o zretune zretune.o audiofile.o dither.o -lzita-resampler -lsndfile -lrt
/home/softin/Work/RASP/build/tmp/sysroots/x86_64-linux/usr/libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/5.4.0/ld: warning: library search path "/usr/local/lib64" is unsafe for cross-compilation
/home/softin/Work/RASP/build/tmp/sysroots/x86_64-linux/usr/libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/5.4.0/ld: warning: library search path "/usr/local/lib64" is unsafe for cross-compilation
DEBUG: Shell function do_compile finished

**Comment by schnitzeltony** [comment]
Interesting: My log.do_compile contains same but does not complain - so I can reproduce. Will look into tomorrow.

**Comment by schnitzeltony** [comment]
Should be fixed by cc9fc64e. Wonder what I have to change to get same errors...

If it does not fix for you please re-open this issue

**Comment by MaxPayne86** [comment]
Solved! Thanks a lot
