### ISSUE TITLE
Startkde gets in crashloop

### ISSUE THREAD

**Issue by megastallman** [schnitzeltony/meta-qt5-extra#54]
Hi @schnitzeltony !

After running startkde I get:
```KActivities: FATAL ERROR: Failed to contact the activity manager daemon
KActivities: FATAL ERROR: Failed to contact the activity manager daemon
KActivities: FATAL ERROR: Failed to contact the activity manager daemon
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 12396, resource id:  4194309, major code: 18 (Change Property), minor code: 0
```
crashlooping.

When I run Xfce4 and try "kactivitymanagerd start" - it says no SQLite driver found, even if add sqlite3 to my packages.
```
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers:
QSqlError: ("", "Driver not loaded", "Driver not loaded")
Service started, version:
```

Thanks  in advance!

**Comment by schnitzeltony** [comment]
Hi,

Last time I tried kde plasma, it worked without issues - more or less. Currently kwallet fails to compile here so I cannot test. Can you please drop me:

* Your build configuration
* kactivitymanagerd's log.do_configure / log.do_compile

With that I can see what's different at your builds and which changes might fix.

**Comment by schnitzeltony** [comment]
A coffee later: Try da916a2396bd912d1cb2f27f3e009a5181dc2767

**Comment by megastallman** [comment]
Hi @schnitzeltony !
Thanks much! Now I have a working plasma desktop!!!! At last!
I've been building a kde-world metapackage, but without some dependencies I've excluded:
- kde-games - I'm not this guy.
- minuet - Timidity is broken, and that is the only package requiring it
- recipes-kde/plasma/untier/oxygen-fonts/oxygen-fonts.bb points to a broken link, so I've added
SRC_URI = "https://ftp.osuosl.org/pub/blfs/conglomeration/oxygen-fonts/oxygen-fonts-5.4.3.tar.xz" there.

**Comment by schnitzeltony** [comment]
Hi @megastallman, 

> Thanks much! Now I have a working plasma desktop!!!!

Cool - happy users makes me happy :)

> minuet - Timidity is broken, and that is the only package requiring it

What do you mean by broken? Does timidity not build or is it some run issue?

> recipes-kde/plasma/untier/oxygen-fonts/oxygen-fonts.bb points to a broken link...

Will check that

Thanks for feedback

**Comment by megastallman** [comment]
Timidity didn't last week. I think I'll try it again to get logs.
