### ISSUE TITLE
Warrior support

### ISSUE THREAD

**Issue by schultzern** [schnitzeltony/meta-qt5-extra#71]
Are you planning to support the warrior release :) ?

**Comment by schnitzeltony** [comment]
Yes but have a different timing than major layers: in my layers I create stable branches as late as possible - means when modifications make layer incompatible to latest stable branch (this time warrior). I do this to have the latests updates included in last release and to reduce my maintenance efforts (have 5 layers - meta-raspi-light excluded).

FWIW: My productive builds are based on oe-core warrior (oe-core master is just build tested from time to time)

If you know of issues or have strong reasons that make it necessary to create warrior soon - please let me know.

**Comment by schultzern** [comment]
Thanks for the info! I don't have any specific reason for updating right now other than wanting to go to the "latest" when I do. I'll keep checking in. 

Thank you for maintaining this layer!

**Comment by schnitzeltony** [comment]
Just created warrior branch
