### ISSUE TITLE
KArchiveFile data() returns less data then size()

### ISSUE THREAD

**Issue by kpopv** [schnitzeltony/meta-qt5-extra#86]
I'm experiencing a bug with KArchive 5.73 in the dunfell branch which I reported to KDE: https://bugs.kde.org/show_bug.cgi?id=437778 . However, it appears this bug isn't triggered when building the same KArchive from source so I'm looking into whether this is something yocto specific. 

Attached is a minimal example [tst_KArchiveTest.txt](https://github.com/schnitzeltony/meta-qt5-extra/files/6616468/tst_KArchiveTest.txt) to reproduce the issue. Is someone able to confirm whether or not this is an issue?

> FAIL!  : KArchiveTest::sizeVsDataDiscrepancy() Compared values are not the same
   Actual   (file1->data().size()): 5685248
   Expected (data1.size())        : 5757690
   Loc: [tst_KArchiveTest.cpp(56)]

**Comment by dev-0x7C6** [comment]
Maybe libraries that're used by it causing problem? Like you suggested libz, maybe it's worth to try different versions? https://layers.openembedded.org/layerindex/recipe/89425/

Not sure if KArchive is using libz for zip files, but probably is.

**Comment by kpopv** [comment]
Thank you for the suggestion, indeed, it seems related to the specific libz we're using:

- libz.so.1.2.11: OK
- libz.so.1.2.11.1-motley: NOT OK

I've filed a bug against that specific version's project: https://github.com/jtkukunas/zlib/issues/33

**Comment by schnitzeltony** [comment]
Just for the record: As soon as I can be of support - let me know :parking:

**Comment by kpopv** [comment]
As we've verified https://github.com/jtkukunas/zlib/issues/33 is the root cause, this issue can be closed. Thank you for the support!
